<?php
/**
 * @file
 * Edit XML using a lightweight javascript editor.
 */

/**
 * Functions for defining this as a widget
 */
require_once drupal_get_path('module', 'jquery_xmleditor') . '/includes/widget.inc';

/**
 * Implements hook_menu().
 */
function jquery_xmleditor_menu() {
  return array(
    'admin/config/content/jquery_xmleditor' => array(
      'title' => 'jquery.xmleditor',
      'description' => 'Configure the jquery.xmleditor',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('jquery_xmleditor_admin'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin_form.inc',
    ),
    'jquery_xmleditor/schemas/%' => array(
      'title' => 'Ajax pass through for Schema',
      'page callback' => 'jquery_xmleditor_get_json',
      'page arguments' => array(2),
      'type' => MENU_CALLBACK,
      'access callback' => TRUE,
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function jquery_xmleditor_libraries_info() {
  return array(
    'jquery.xmleditor' => array(
      'name' => 'jquery.xmleditor',
      'vendor url' => 'https://github.com/UNC-Libraries/jquery.xmleditor',
      'download url' => 'https://github.com/UNC-Libraries/jquery.xmleditor',
      'version' => '1.x',
      'files' => array(
        'js' => array(
          'lib/ace/src-min/ace.js',
          'lib/json2.js',
          'lib/cycle.js',
          'lib/jquery.autosize-min.js',
          'lib/vkbeautify.js',
          'xsd/xsd2json.js',
          'jquery.xmleditor.js',
        ),
        'css' => array(
          'css/jquery.xmleditor.css',
        ),
      ),

    ),
  );
}

/**
 * Simple redirect for jquery.xmleditor Ajax request to get schema documents.
 */
function jquery_xmleditor_get_json($file_id) {
  $results = db_query("SELECT json_schema FROM {jquery_xmleditor_schemas} WHERE id = :id", array(':id' => $file_id));
  if ($results->rowCount() > 0) {
    $result = $results->fetchObject();
    $json_file = $result->json_schema;
    drupal_goto($result->json_schema);
  }
}
